package taller.pkg1.natalia.muñoz.manzo;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.JLabel;

public class InterfazTaller extends javax.swing.JFrame {
    
    public InterfazTaller() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
//        JLabel.setForeground(.red); 
        
    }
    public static void menuPrincipal(){
        int opcion;
        Scanner entrada = new Scanner(System.in);
        System.out.print("1.Nombres\n"
        + "2.Libros");
        System.out.println("Digite opción deseada:");
        opcion = entrada.nextInt();
        switch (opcion) {
            case 1:
                nombres();
                break;
            case 2:
                libros();
                break;
            default:
                System.out.println("Digite opción válida!!");
                menuPrincipal();
        } 
    
    }
        public static void nombres() {
        Scanner entrada = new Scanner(System.in);
        String[][] personas = new String[3][3];
        for (int x = 0; x < personas.length; x++) {
            for (int y = 0; y < personas[x].length; y++) {
                System.out.println("Introduzca el nombre [" + x + "," + y + "]");
                personas[x][y] = entrada.nextLine();
            }
        }
        for (int x = 0; x < personas.length; x++) {
            for (int y = 0; y < personas[x].length; y++) {
                System.out.println("[" + x + "," + y + "] = " + personas[x][y]);
            }
        }
        for (int x = 0; x < personas.length; x++) {
            for (int y = 0; y < personas[x].length; y++) {
                if (personas[x][y] == "C" && personas[x][y] == "G") {
                    String cadena = "[x][y]";
                    System.out.println(cadena.charAt(0));
                    
                }
            }
        }

    }
        public static void libros() {
            String lista;
            Scanner entrada = new Scanner(System.in);
            System.out.println("Digite el nombre del libro deseado");
            lista = entrada.nextLine();
            
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuIni = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        nombrePerso = new javax.swing.JMenuItem();
        listaLibros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuIni.setText("Inicio");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuIni.add(menuSalir);

        jMenuBar1.add(menuIni);

        jMenu2.setText("Ejercicios");

        nombrePerso.setText("Nombres");
        nombrePerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePersoActionPerformed(evt);
            }
        });
        jMenu2.add(nombrePerso);

        listaLibros.setText("Libros");
        jMenu2.add(listaLibros);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void nombrePersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePersoActionPerformed
        nombres();
    }//GEN-LAST:event_nombrePersoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTaller().setVisible(true);
                              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaLibros;
    private javax.swing.JMenu menuIni;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem nombrePerso;
    // End of variables declaration//GEN-END:variables
}
